# Generated by Django 5.0.7 on 2024-11-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Singer',
            new_name='singer',
        ),
    ]
